### ISSUE TITLE
several problems with root

### ISSUE THREAD

**Issue by DF1E** [DF1E/SimpleExplorer#33]
In some directories couldn't work with root because of SELinux. I will add more infos when I have more time..

**Comment by danielmmmm** [comment]
Thanks a lot for digging into this issue! :-)

**Comment by maysleazy** [comment]
Faced the same issue, hope you fix it in newer build. Props for the File Browser, will help as soon as exams are over :)

**Comment by DF1E** [comment]
I fixed the root issues while deleting folder and the group/owner dialog.. Do you experience more bugs with root??

**Comment by maysleazy** [comment]
Fixed :) :+1:

**Comment by danielmmmm** [comment]
> Do you experience more bugs with root??
Hm, I would have to test first :-)

Thanks a lot for fixing this!

**Comment by Anandababu** [comment]
I'm still having the root issues. 

Unable to delete folders in system folder. Says deleted successfully but folders are not deleted. About to delete only individual files. Using version 2.5.5.

AOSP Lollipop 5.1 ROM.
Xiaomi Mi3.
